version: "3.9"
services:
  ros2:
    build: .
  #  network_mode: "host"
    # restart: no
  #  ports: 
    #  - "11811:11811" # node discoverer
    volumes:
    # relative PATH which SHULD work when coupled with our GIT repository
    # https://github.com/revalew/HEXAPOD.git
      - ../.:/home/ros
    devices:
      # USB device - where our USB to TTL converter is connected
      - /dev/ttyUSB0:/dev/ttyUSB0
      # - /dev/ttyUSB1:/dev/ttyUSB1
# Enable the terminal - without it it would constantly pop up and close
    tty: true
